import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

// generated by shadcn
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const mapToStringArray = (options : any, values : any) => {
  return options.filter((option : any) => values.includes(option.name));
};
